import React from 'react'
import { Row, Col } from 'antd'
import { Typography } from '@material-ui/core'
import Navigation from '../../components/Navigation'
import FooterApp from '../../components/FooterApp'
import './index.css'

function Privacy() {
	return (
		<div>
			<Navigation />
			<div className="container">
				<Row>
					<Col xs={24} sm={24} md={24} span={24}>
						<Typography variant="h6" gutterBottom>
							Privacy Policy
						</Typography>
						<Typography variant="body2" gutter Bottom>
							LINK UP ("us", "we", or "our") operates the Link up website (the "Service").
							This page informs you of our policies regarding the collection, use, and
							disclosure of personal data when you use our Service and the choices you have
							associated with that data. We use your data to provide and improve the
							Service. <br />
							By using the Service, you agree to the collection and use of information in
							accordance with this policy. Unless otherwise defined in this Privacy Policy,
							terms used in this Privacy Policy have the same meanings as in our Terms and
							Conditions, accessible from Link up. <br />
							<strong>Service</strong>
							<br />
							Service is the Link up website operated by LINK UP
							<br />
							<br />
							<strong>Personal Data</strong>
							<br />
							Personal Data means data about a living individual who can be identified from
							those data (or from those and other information either in our possession or
							likely to come into our possession).
							<br />
							<br />
							<strong>Usage Data</strong>
							<br />
							Usage Data is data collected automatically either generated by the use of the
							Service or from the Service infrastructure itself (for example, the duration
							of a page visit).
							<br />
							<br />
							<strong>Cookies</strong>
							<br />
							Cookies are small pieces of data stored on your device (computer or mobile
							device).
							<br />
							<br />
							<strong>Data Controller</strong>
							<br />
							Data Controller means the natural or legal person who (either alone or jointly
							or in common with other persons) determines the purposes for which and the
							manner in which any personal information are, or are to be, processed. For the
							purpose of this Privacy Policy, we are a Data Controller of your Personal
							Data.
							<br />
							<br />
							<strong>Data Processors (or Service Providers)</strong>
							<br />
							Data Processor (or Service Provider) means any natural or legal person who
							processes the data on behalf of the Data Controller. We may use the services
							of various Service Providers in order to process your data more effectively.
							<br />
							<br />
							<strong>Data Subject</strong>
							<br />
							Data Subject is any living individual who is using our Service and is the
							subject of Personal Data.
							<br />
							<br />
							<strong>Information Collection and Use</strong>
							<br />
							We collect several different types of information for various purposes to
							provide and improve our Service to you.
							<br />
							<br />
							<strong>Personal Data</strong>
							<br />
							While using our Service, we may ask you to provide us with certain personally
							identifiable information that can be used to contact or identify you
							("Personal Data"). Personally identifiable information may include, but is not
							limited to:
							<br />
							<ul>
								<li>Email address</li>
								<li>First and last name</li>
								<li>Social media URLs or usernames</li>
								<li>Credit card expiration/type/name</li>
							</ul>
							<br />
							<strong>Usage Data</strong>
							<br />
							We may also collect information how the Service is accessed and used ("Usage
							Data"). This Usage Data may include information such as your computer's
							Internet Protocol address (e.g. IP address), browser type, browser version,
							the pages of our Service that you visit, the time and date of your visit, the
							time spent on those pages, unique device identifiers and other diagnostic
							data.
							<br />
							Your IP address is never stored in our database, we use your IP to obtain
							general and anonymised data about your profile end users such as approximate
							geo-location e.g country, city.
							<br />
							<br />
							<strong>Location Data</strong>
							<br />
							We may use and store information about your location if you give us permission
							to do so (“Location Data”). We use this data to provide features of our
							Service, to improve and customize our Service. We may use and store
							information about visitors to Link up Profiles. This is anonymised and
							aggregated in high quantities, removing any Personally Identifiable
							information as we are interested in the ‘how’ more than the ‘who’.
							<br />
							<br />
							<strong>Tracking Cookies Data</strong>
							<br />
							We may use and store information about your location if you give us permission
							to do so (“Location Data”). We use this data to provide features of our
							Service, to improve and customize our Service. We may use and store
							information about visitors to Link up Profiles. This is anonymised and
							aggregated in high quantities, removing any Personally Identifiable
							information as we are interested in the ‘how’ more than the ‘who’.
							<br />
							Examples of cookies we use:
							<ul>
								<li>
									Session Cookies. We use Session Cookies to operate and retain user
									authentication with the service.
								</li>
								<li>
									Preference Cookies. We use Preference Cookies to remember your preferences
									and acceptance of our policies.
								</li>
								<li>Analytics Cookies. Google/Facebook analytics.</li>
							</ul>
							<br />
							More information on our use of cookies can be found on our Cookies Policy.{' '}
							<br />
							<br />
							<strong>Use of Data</strong>
							<br />
							Uses the collected data for various purposes:
							<br />
							<ul>
								<li>To provide and maintain our Service</li>
								<li>To notify you of changes to our Service</li>
								<li>
									To allow you to participate in interactive features of our Service when
									you choose to do so
								</li>
								<li>To provide customer support</li>
								<li>
									To gather analysis or valuable information so that we can improve our
									Service
								</li>
								<li>To monitor the usage of our Service</li>
								<li>To detect, address, and prevent technical issues</li>
								<li>
									To provide you with news, special offers and general information about
									other goods, services and events which we offer that are similar to those
									that you have already purchased or enquired about unless you have opted
									not to receive such information
								</li>
							</ul>
							<br />
							<strong>
								Legal Basis for Processing Personal Data Under General Data Protection
								Regulation (GDPR)
							</strong>
							<br />
							If you are from the European Economic Area (EEA), LINK UP legal basis for
							collecting and using the personal information described in this Privacy Policy
							depends on the Personal Data we collect and the specific context in which we
							collect it. LINK UP may process your Personal Data because:
							<br />
							<ul>
								<li>We need to perform a contract with you</li>
								<li>You have given us permission to do so</li>
								<li>
									The processing is in our legitimate interests and it's not overridden by
									your rights
								</li>
								<li>For payment processing purposes</li>
								<li>To comply with the law</li>
							</ul>
							<br />
							<strong>Retention of Data</strong>
							<br />
							LINK UP will retain your Personal Data only for as long as is necessary for
							the purposes set out in this Privacy Policy. We will retain and use your
							Personal Data to the extent necessary to comply with our legal obligations
							(for example, if we are required to retain your data to comply with applicable
							laws), resolve disputes, and enforce our legal agreements and policies. LINK
							UP will also retain Usage Data for internal analysis purposes. Usage Data is
							generally retained for a shorter period of time, except when this data is used
							to strengthen the security or to improve the functionality of our Service, or
							we are legally obligated to retain this data for longer time periods.
							<br />
							<br />
							<strong>Transfer of Data</strong>
							<br />
							Your information, including Personal Data, may be transferred to — and
							maintained on — computers located outside of your state, province, country or
							other governmental jurisdiction where the data protection laws may differ than
							those from your jurisdiction. If you are located outside of Europe and choose
							to provide information to us, please note that we transfer the data, including
							Personal Data, to The United States of America and process it there.
							<br />
							Link up is operated out of an office in Canada. Whilst all servers and data is
							stored in the United States of America, we are executing the processing and
							security of data from Canadian personnel. Your consent to this Privacy Policy
							followed by your submission of such information represents your agreement to
							that transfer. LINK UP will take all steps reasonably necessary to ensure that
							your data is treated securely and in accordance with this Privacy Policy and
							no transfer of your Personal Data will take place to an organization or a
							country unless there are adequate controls in place including the security of
							your data and other personal information.
							<br />
							<br />
							<strong>Business Transaction</strong>
							<br />
							If LINK UP is involved in a merger, acquisition or asset sale, your Personal
							Data may be transferred. We will provide notice when your Personal Data is
							transferred and becomes subject to a different Privacy Policy.
							<br />
							<br />
							<strong>Disclosure for Law Enforcement</strong>
							<br />
							Under certain circumstances, LINK UP may be required to disclose your Personal
							Data if required to do so by law or in response to valid requests by public
							authorities (e.g. a court or a government agency).
							<br />
							<br />
						</Typography>
					</Col>
				</Row>
				<FooterApp />
			</div>
		</div>
	)
}

export default Privacy
